version: 2
updates:
  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'daily'
    assignees:
      - 'aeswibon'
    labels:
      - 'ci'
      - 'dependencies'

  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'daily'
    allow:
      - dependency-name: '*'
      - dependency-type: 'production'
    assignees:
      - 'aeswibon'
    labels:
      - 'npm'
      - 'dependencies'
